#!/usr/bin/env node

/**
 * Yakmesh CLI
 * Command-line interface for managing Yakmesh nodes
 */

import { Command } from 'commander';
import chalk from 'chalk';
import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'fs';
import { join, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const VERSION = '0.1.0';

const program = new Command();

// Banner
function showBanner() {
  console.log(chalk.cyan(`
  🦬 Yakmesh Network v${VERSION}
  Post-Quantum Secure • Decentralized • Federated
  `));
}

// ===== INIT COMMAND =====
program
  .command('init')
  .description('Initialize a new Yakmesh Node in the current directory')
  .option('-n, --name <name>', 'Node name', 'My Yakmesh Node')
  .option('-r, --region <region>', 'Geographic region', 'local')
  .option('-p, --port <port>', 'HTTP port', '3000')
  .option('-w, --ws-port <port>', 'WebSocket port', '9001')
  .option('--bootstrap <urls>', 'Comma-separated bootstrap node URLs')
  .action(async (options) => {
    showBanner();
    console.log(chalk.yellow('Initializing new Yakmesh Node...\n'));

    const dataDir = resolve('./data');
    const configPath = resolve('./yakmesh.config.js');

    // Check if already initialized
    if (existsSync(configPath)) {
      console.log(chalk.red('✗ Error: yakmesh.config.js already exists'));
      console.log(chalk.gray('  Use --force to reinitialize'));
      process.exit(1);
    }

    // Create data directory
    if (!existsSync(dataDir)) {
      mkdirSync(dataDir, { recursive: true });
      console.log(chalk.green('✓ Created data directory'));
    }

    // Parse bootstrap nodes
    const bootstrapNodes = options.bootstrap 
      ? options.bootstrap.split(',').map(s => s.trim())
      : [];  // Empty by default - YAKMESH is decentralized, no central bootstrap

    // Generate config
    const config = `/**
 * Yakmesh Node Configuration
 * Generated by: npx yakmesh init
 */
export default {
  // Node identity
  node: {
    name: '${options.name}',
    region: '${options.region}',
    capabilities: ['listings', 'chat', 'forum', 'qcoa'],
  },
  
  // Network settings
  network: {
    httpPort: ${options.port},
    wsPort: ${options.wsPort},
    publicHost: 'localhost',
  },
  
  // Bootstrap nodes (well-known entry points)
  bootstrap: ${JSON.stringify(bootstrapNodes, null, 4).replace(/\n/g, '\n  ')},
  
  // Database
  database: {
    path: './data/peerquanta.db',
    replication: {
      enabled: true,
      syncInterval: 30000,  // 30 seconds
    },
  },
  
  // Security
  security: {
    maxPeers: 50,
    requireAuth: false,
  },
};
`;

    writeFileSync(configPath, config);
    console.log(chalk.green('✓ Created yakmesh.config.js'));

    console.log(chalk.cyan('\n📋 Node Configuration:'));
    console.log(chalk.gray(`   Name:       ${options.name}`));
    console.log(chalk.gray(`   Region:     ${options.region}`));
    console.log(chalk.gray(`   HTTP Port:  ${options.port}`));
    console.log(chalk.gray(`   WS Port:    ${options.wsPort}`));
    console.log(chalk.gray(`   Bootstrap:  ${bootstrapNodes.length} node(s)`));

    console.log(chalk.green('\n✓ Initialization complete!\n'));
    console.log(chalk.white('Next steps:'));
    console.log(chalk.gray('  1. Edit yakmesh.config.js to customize settings'));
    console.log(chalk.gray('  2. Run: npx yakmesh start'));
    console.log('');
  });

// ===== START COMMAND =====
program
  .command('start')
  .description('Start the Yakmesh Node')
  .option('-c, --config <path>', 'Path to config file', './yakmesh.config.js')
  .option('-d, --daemon', 'Run as background daemon')
  .action(async (options) => {
    showBanner();
    
    const configPath = resolve(options.config);
    
    if (!existsSync(configPath)) {
      console.log(chalk.red('✗ Error: yakmesh.config.js not found'));
      console.log(chalk.gray('  Run: npx yakmesh init'));
      process.exit(1);
    }

    console.log(chalk.yellow('Starting Yakmesh Node...\n'));

    // Dynamic import of server - use the package's server module
    const serverPath = join(__dirname, '..', 'server', 'index.js');
    const serverURL = new URL(`file:///${serverPath.replace(/\\/g, '/')}`);
    const { YakmeshNode } = await import(serverURL.href);
    
    // Load config from current working directory
    const configURL = new URL(`file:///${configPath.replace(/\\/g, '/')}`);
    const { default: config } = await import(configURL.href);

    const node = new YakmeshNode(config);

    // Handle shutdown
    process.on('SIGINT', async () => {
      console.log(chalk.yellow('\n\nShutting down...'));
      await node.stop();
      process.exit(0);
    });

    process.on('SIGTERM', async () => {
      await node.stop();
      process.exit(0);
    });

    await node.start();
  });

// ===== STATUS COMMAND =====
program
  .command('status')
  .description('Show node status')
  .option('-p, --port <port>', 'HTTP port of local node', '3000')
  .action(async (options) => {
    try {
      const response = await fetch(`http://localhost:${options.port}/health`);
      const data = await response.json();

      showBanner();
      console.log(chalk.green('✓ Node is running\n'));
      console.log(chalk.cyan('📊 Status:'));
      console.log(chalk.gray(`   Node ID:    ${data.nodeId}`));
      console.log(chalk.gray(`   Peers:      ${data.peers}`));
      console.log(chalk.gray(`   Algorithm:  ${data.algorithm}`));
      console.log('');
    } catch (e) {
      console.log(chalk.red('✗ Node is not running'));
      console.log(chalk.gray(`  Could not connect to http://localhost:${options.port}`));
      process.exit(1);
    }
  });

// ===== PEERS COMMAND =====
program
  .command('peers')
  .description('List connected peers')
  .option('-p, --port <port>', 'HTTP port of local node', '3000')
  .action(async (options) => {
    try {
      const response = await fetch(`http://localhost:${options.port}/peers`);
      const peers = await response.json();

      showBanner();
      
      if (peers.length === 0) {
        console.log(chalk.yellow('No peers connected\n'));
        return;
      }

      console.log(chalk.cyan(`📡 Connected Peers (${peers.length}):\n`));
      
      for (const peer of peers) {
        const ago = Math.floor((Date.now() - peer.lastSeen) / 1000);
        console.log(chalk.white(`  ${peer.name}`));
        console.log(chalk.gray(`    ID:        ${peer.nodeId.slice(0, 24)}...`));
        console.log(chalk.gray(`    Endpoint:  ${peer.endpoint || 'inbound'}`));
        console.log(chalk.gray(`    Last seen: ${ago}s ago`));
        console.log('');
      }
    } catch (e) {
      console.log(chalk.red('✗ Could not fetch peers'));
      console.log(chalk.gray(`  Is the node running on port ${options.port}?`));
      process.exit(1);
    }
  });

// ===== INFO COMMAND =====
program
  .command('info')
  .description('Show detailed node information')
  .option('-p, --port <port>', 'HTTP port of local node', '3000')
  .action(async (options) => {
    try {
      const [nodeRes, replRes] = await Promise.all([
        fetch(`http://localhost:${options.port}/node`),
        fetch(`http://localhost:${options.port}/replication`),
      ]);
      
      const node = await nodeRes.json();
      const repl = await replRes.json();

      showBanner();
      console.log(chalk.cyan('🦬 Node Information:\n'));
      
      console.log(chalk.white('  Identity:'));
      console.log(chalk.gray(`    Node ID:      ${node.nodeId}`));
      console.log(chalk.gray(`    Name:         ${node.name}`));
      console.log(chalk.gray(`    Region:       ${node.region}`));
      console.log(chalk.gray(`    Algorithm:    ${node.algorithm} (NIST Level ${node.nistLevel})`));
      console.log(chalk.gray(`    Created:      ${new Date(node.createdAt).toISOString()}`));
      
      console.log(chalk.white('\n  Capabilities:'));
      for (const cap of node.capabilities) {
        console.log(chalk.gray(`    • ${cap}`));
      }
      
      console.log(chalk.white('\n  Replication:'));
      console.log(chalk.gray(`    Log entries:  ${repl.replicationLogSize}`));
      console.log(chalk.gray(`    Peer states:  ${repl.peerStates.length}`));
      console.log(chalk.gray(`    Tables:       ${repl.replicatedTables.join(', ')}`));
      
      console.log(chalk.white('\n  Public Key (ML-DSA-65):'));
      console.log(chalk.gray(`    ${node.publicKey.slice(0, 64)}...`));
      console.log('');
    } catch (e) {
      console.log(chalk.red('✗ Could not fetch node info'));
      process.exit(1);
    }
  });

// ===== JOIN COMMAND =====
program
  .command('join <endpoint>')
  .description('Connect to a peer node')
  .option('-p, --port <port>', 'HTTP port of local node', '3000')
  .action(async (endpoint, options) => {
    try {
      const response = await fetch(`http://localhost:${options.port}/connect`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ endpoint }),
      });
      
      const result = await response.json();
      
      if (result.success) {
        console.log(chalk.green(`✓ Connected to ${endpoint}`));
      } else {
        console.log(chalk.red(`✗ Failed to connect: ${result.error}`));
      }
    } catch (e) {
      console.log(chalk.red('✗ Could not connect'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

// ===== VERSION =====
program
  .version(VERSION)
  .description('Yakmesh Network - Post-Quantum Decentralized Node');

// Parse arguments
program.parse();

// Show help if no command
if (!process.argv.slice(2).length) {
  showBanner();
  program.outputHelp();
}



