#!/usr/bin/env node
/*
 * YAKMESH™: Yielding Atomic Kernel Modular Encryption Secured Hub
 * Copyright (C) 2026 YAKMESH™ / [JGP]
 *
 * TRADEMARK NOTICE:
 * YAKMESH™ is a trademark of PeerQuanta, application pending (Serial No. 99594620).
 * Unauthorized use of the YAKMESH™ name, logo, or branding is strictly prohibited.
 *
 * LICENSE:
 * This Source Code Form is subject to the terms of the YAKMESH
 * NETWORK ENGINE LICENSE AGREEMENT, v. 1.0. If a copy of that
 * license agreement was not distributed with this file, You can
 * find a link to the license at https://yakmesh.dev/license
 *
 * This Source Code Form is "Incompatible With Secondary Licenses",
 * as defined by the YAKMESH NETWORK ENGINE LICENSE AGREEMENT, v. 1.0.
 *
 * "The standard is binary. The reality is ternary. The resonance is 432."
 */

/**
 * Yakmesh CLI
 * Command-line interface for managing Yakmesh nodes
 */

import { Command } from 'commander';
import chalk from 'chalk';
import { existsSync, mkdirSync, writeFileSync, readFileSync, cpSync, readdirSync, renameSync } from 'fs';
import { join, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const VERSION = JSON.parse(readFileSync(join(__dirname, '..', 'package.json'), 'utf8')).version;

const program = new Command();

// Banner
function showBanner() {
  console.log(chalk.cyan(`
  🦬 Yakmesh Network v${VERSION}
  Post-Quantum Secure • Decentralized • Federated
  `));
}

// ===== INIT COMMAND =====
program
  .command('init')
  .description('Initialize a new Yakmesh Node in the current directory')
  .option('-n, --name <name>', 'Node name', 'My Yakmesh Node')
  .option('-r, --region <region>', 'Geographic region', 'local')
  .option('-p, --port <port>', 'HTTP port', '3080')
  .option('-w, --ws-port <port>', 'WebSocket port', '9080')
  .option('--bootstrap <urls>', 'Comma-separated bootstrap node URLs')
  .action(async (options) => {
    showBanner();
    console.log(chalk.yellow('Initializing new Yakmesh Node...\n'));

    const dataDir = resolve('./data');
    const configPath = resolve('./yakmesh.config.js');

    // Check if already initialized
    if (existsSync(configPath)) {
      console.log(chalk.red('✗ Error: yakmesh.config.js already exists'));
      console.log(chalk.gray('  Use --force to reinitialize'));
      process.exit(1);
    }

    // Create data directory
    if (!existsSync(dataDir)) {
      mkdirSync(dataDir, { recursive: true });
      console.log(chalk.green('✓ Created data directory'));
    }

    // Parse bootstrap nodes
    const bootstrapNodes = options.bootstrap 
      ? options.bootstrap.split(',').map(s => s.trim())
      : [];  // Empty by default - YAKMESH is decentralized, no central bootstrap

    // Generate config
    const config = `/**
 * Yakmesh Node Configuration
 * Generated by: npx yakmesh init
 */
export default {
  // Node identity
  node: {
    name: '${options.name}',
    region: '${options.region}',
    capabilities: ['listings', 'chat', 'forum', 'qcoa'],
  },
  
  // Network settings
  network: {
    httpPort: ${options.port},
    wsPort: ${options.wsPort},
    publicHost: 'localhost',
  },
  
  // Bootstrap nodes (well-known entry points)
  bootstrap: ${JSON.stringify(bootstrapNodes, null, 4).replace(/\n/g, '\n  ')},
  
  // Database
  database: {
    path: './data/peerquanta.db',
    replication: {
      enabled: true,
      syncInterval: 30000,  // 30 seconds
    },
  },
  
  // Security
  security: {
    maxPeers: 50,
    requireAuth: false,
  },
};
`;

    writeFileSync(configPath, config);
    console.log(chalk.green('✓ Created yakmesh.config.js'));

    console.log(chalk.cyan('\n📋 Node Configuration:'));
    console.log(chalk.gray(`   Name:       ${options.name}`));
    console.log(chalk.gray(`   Region:     ${options.region}`));
    console.log(chalk.gray(`   HTTP Port:  ${options.port}`));
    console.log(chalk.gray(`   WS Port:    ${options.wsPort}`));
    console.log(chalk.gray(`   Bootstrap:  ${bootstrapNodes.length} node(s)`));

    console.log(chalk.green('\n✓ Initialization complete!\n'));
    console.log(chalk.white('Next steps:'));
    console.log(chalk.gray('  1. Edit yakmesh.config.js to customize settings'));
    console.log(chalk.gray('  2. Run: npx yakmesh start'));
    console.log('');
  });

// ===== MIGRATE COMMAND =====
// Files that are runtime-volatile or machine-specific — never carried forward.
const MIGRATE_SKIP = new Set([
  'pending-update', 'packages', 'act-restart.json',
  'supervisor.log', 'node.log', 'supervisor.log.old',
]);

function readPersistentId(dataDir) {
  try {
    const seed = JSON.parse(readFileSync(join(dataDir, 'machine-seed.json'), 'utf8'));
    return seed.persistentId || null;
  } catch {
    return null;
  }
}

program
  .command('migrate')
  .description('Carry identity + state forward from a previous install (replaces manual data-dir linking)')
  .argument('<source>', 'Previous install dir or data dir (e.g. ../yakmesh-3.5.9 or .../data)')
  .option('-t, --to <dir>', 'Target data directory', './data')
  .option('-f, --force', 'Overwrite existing identity in target')
  .option('--dry-run', 'Show what would be copied without copying')
  .action(async (source, options) => {
    showBanner();
    console.log(chalk.yellow('Yakmesh identity migration\n'));

    // Accept either the install root or the data dir itself
    let srcDir = resolve(source);
    if (existsSync(join(srcDir, 'data', 'machine-seed.json'))) {
      srcDir = join(srcDir, 'data');
    }
    const dstDir = resolve(options.to);

    if (!existsSync(srcDir)) {
      console.log(chalk.red(`✗ Source not found: ${source}`));
      process.exit(1);
    }
    if (!existsSync(join(srcDir, 'node-key.json')) && !existsSync(join(srcDir, 'machine-seed.json'))) {
      console.log(chalk.red(`✗ No Yakmesh identity in ${srcDir}`));
      console.log(chalk.gray('  Expected node-key.json or machine-seed.json'));
      process.exit(1);
    }

    const srcPid = readPersistentId(srcDir);
    const dstPid = readPersistentId(dstDir);

    if (existsSync(join(dstDir, 'node-key.json')) && !options.force) {
      console.log(chalk.red('✗ Target already has an identity (node-key.json exists)'));
      console.log(chalk.gray(`  Target persistentId: ${dstPid || 'unknown'}`));
      console.log(chalk.gray('  Use --force to overwrite (old identity will be lost)'));
      process.exit(1);
    }

    // Collect entries to copy
    const entries = readdirSync(srcDir, { withFileTypes: true })
      .filter(e => !MIGRATE_SKIP.has(e.name));

    console.log(chalk.gray(`  Source:      ${srcDir}`));
    console.log(chalk.gray(`  Target:      ${dstDir}`));
    console.log(chalk.gray(`  persistentId: ${srcPid || '(none found)'}`));
    console.log(chalk.gray(`  Entries:     ${entries.length}`));

    if (options.dryRun) {
      for (const e of entries) console.log(chalk.gray(`    ${e.isDirectory() ? 'd' : '-'} ${e.name}`));
      console.log(chalk.cyan('\nDry run — nothing copied.'));
      return;
    }

    if (srcPid && dstPid && srcPid !== dstPid) {
      console.log(chalk.yellow(`\n⚠ Target persistentId differs (${dstPid}) — it will be replaced.`));
    }

    mkdirSync(dstDir, { recursive: true });
    let copied = 0, skipped = 0;
    for (const e of entries) {
      const s = join(srcDir, e.name), d = join(dstDir, e.name);
      try {
        cpSync(s, d, { recursive: true, errorOnExist: false, force: true });
        copied++;
      } catch (err) {
        skipped++;
        console.log(chalk.yellow(`  ⚠ skipped ${e.name}: ${err.message}`));
      }
    }

    // Verify the carried identity
    const newPid = readPersistentId(dstDir);
    if (srcPid && newPid !== srcPid) {
      console.log(chalk.red('\n✗ Verification failed: persistentId did not survive the copy'));
      process.exit(1);
    }

    console.log(chalk.green(`\n✓ Migrated ${copied} entries${skipped ? ` (${skipped} skipped)` : ''}`));
    if (newPid) console.log(chalk.green(`✓ persistentId verified: ${newPid}`));
    console.log(chalk.gray('\nNote: upgrade-grace will hold any manifest-mismatched files for review on first boot — that is expected on an upgrade.'));
    console.log('');
  });

// ===== IDENTITY COMMAND GROUP =====
const identityCmd = program
  .command('identity')
  .description('Inspect or reset this node\'s hardware-bound identity');

identityCmd
  .command('show')
  .description('Show persistentId and seed state')
  .option('-t, --to <dir>', 'Data directory', './data')
  .action((options) => {
    showBanner();
    const dataDir = resolve(options.to);
    const seedPath = join(dataDir, 'machine-seed.json');
    const keyPath = join(dataDir, 'node-key.json');
    const pid = readPersistentId(dataDir);

    console.log(chalk.yellow('Node identity\n'));
    console.log(chalk.gray(`  Data dir:     ${dataDir}`));
    console.log(chalk.gray(`  persistentId: ${pid || '(none)'}`));
    console.log(chalk.gray(`  Seed file:    ${existsSync(seedPath) ? 'present (hardware-encrypted)' : 'absent — will mint on next start'}`));
    console.log(chalk.gray(`  Public key:   ${existsSync(keyPath) ? 'present' : 'absent — will derive on next start'}`));

    // Quarantined seeds (auto-recovery or manual reset leftovers)
    if (existsSync(dataDir)) {
      const quarantined = readdirSync(dataDir)
        .filter(f => /^machine-seed\.(invalid|reset)-.*\.json$/.test(f));
      if (quarantined.length) {
        console.log(chalk.gray(`\n  Quarantined seeds:`));
        for (const f of quarantined) console.log(chalk.gray(`    ${f}`));
      }
    }
    console.log('');
  });

identityCmd
  .command('reset')
  .description('Quarantine the current identity so a fresh hardware-bound one is minted on next start')
  .option('-t, --to <dir>', 'Data directory', './data')
  .option('-f, --force', 'Skip confirmation prompt')
  .action(async (options) => {
    showBanner();
    const { createInterface } = await import('node:readline');
    const dataDir = resolve(options.to);
    const seedPath = join(dataDir, 'machine-seed.json');
    const keyPath = join(dataDir, 'node-key.json');
    const pid = readPersistentId(dataDir);

    console.log(chalk.yellow('Reset node identity\n'));
    if (!existsSync(seedPath) && !existsSync(keyPath)) {
      console.log(chalk.gray('  No identity files found — nothing to reset.'));
      console.log(chalk.gray('  A fresh identity is minted on next start anyway.\n'));
      return;
    }

    console.log(chalk.gray(`  Data dir:     ${dataDir}`));
    console.log(chalk.gray(`  persistentId: ${pid || '(unknown)'}`));
    console.log(chalk.yellow('\n  This identity\'s persistentId and KARMA reputation will be LOST.'));
    console.log(chalk.gray('  Files are quarantined (renamed), never deleted.'));
    console.log(chalk.gray('  To keep this identity on new hardware, restore from the 33-word'));
    console.log(chalk.gray('  mnemonic instead (dashboard → Identity Backup).\n'));

    if (!options.force) {
      if (!process.stdin.isTTY) {
        console.log(chalk.red('✗ Non-interactive shell — pass --force to confirm.\n'));
        process.exit(1);
      }
      const rl = createInterface({ input: process.stdin, output: process.stdout });
      const a = await new Promise(r => rl.question('  Reset identity? [y/N] ', r));
      rl.close();
      if (!a.trim().toLowerCase().startsWith('y')) {
        console.log(chalk.gray('  Aborted — identity untouched.\n'));
        return;
      }
    }

    const ts = Date.now();
    let moved = 0;
    for (const p of [seedPath, keyPath]) {
      if (!existsSync(p)) continue;
      const q = p.replace(/\.json$/, `.reset-${ts}.json`);
      try {
        renameSync(p, q);
        moved++;
        console.log(chalk.gray(`  ${p.split(/[\\/]/).pop()} → ${q.split(/[\\/]/).pop()}`));
      } catch (e) {
        console.log(chalk.red(`  ✗ could not quarantine ${p}: ${e.message}`));
      }
    }

    if (moved) {
      console.log(chalk.green(`\n✓ Identity reset (${moved} file(s) quarantined)`));
      console.log(chalk.gray('  Next start mints a fresh hardware-bound persistentId.'));
      console.log(chalk.gray('  Restore the old identity via mnemonic if you have it.\n'));
    } else {
      console.log(chalk.red('\n✗ No files could be quarantined.\n'));
      process.exit(1);
    }
  });

// ===== UPGRADE COMMAND =====
program
  .command('upgrade')
  .description('Apply an upgrade package in place — overlays code, preserves data/ + personal setup')
  .argument('[package]', 'Path to upgrade package (.zip/.tgz) — auto-detected in the install dir, or a file picker opens if omitted')
  .option('--dry-run', 'Show what would be overlaid without applying')
  .option('-y, --yes', 'Accept defaults non-interactively (apply/restart yes, auto-start no)')
  .action(async (pkgPath, options) => {
    showBanner();
    const { zipEntries, applyUpgradePackage, walk, EXCLUDE_DIRS } = await import('../utils/in-place-upgrade.js');
    const { execSync, spawn } = await import('node:child_process');
    const { rmSync, readdirSync, statSync } = await import('node:fs');
    const { createInterface } = await import('node:readline');

    const ROOT = join(__dirname, '..');
    const DATA = join(ROOT, 'data');
    const HTTP_PORT = parseInt(process.env.YAKMESH_HTTP_PORT || '3080', 10);
    const API = `http://127.0.0.1:${HTTP_PORT}`;

    const ask = async (q, defYes = true) => {
      if (options.yes) return defYes;
      if (!process.stdin.isTTY) return defYes;
      const rl = createInterface({ input: process.stdin, output: process.stdout });
      const a = await new Promise(r => rl.question(`${q} ${defYes ? '[Y/n]' : '[y/N]'} `, r));
      rl.close();
      const v = a.trim().toLowerCase();
      return v === '' ? defYes : v.startsWith('y');
    };

    // ── Resolve the package: arg → dir scan → native file picker ──
    let src = pkgPath ? resolve(pkgPath) : null;
    if (!src) {
      const candidates = readdirSync(ROOT)
        .filter(f => /\.(tgz|tar\.gz|zip)$/i.test(f) && /yakmesh|update|upgrade/i.test(f))
        .map(f => ({ f, m: statSync(join(ROOT, f)).mtimeMs }))
        .sort((a, b) => b.m - a.m);
      if (candidates.length) {
        src = join(ROOT, candidates[0].f);
        console.log(chalk.gray(`  Found upgrade package in install dir: ${candidates[0].f}`));
      } else {
        // No package in directory — open the native file picker
        console.log(chalk.gray('  No upgrade package in the install dir — opening file picker…'));
        try {
          if (process.platform === 'linux') {
            src = execSync(`zenity --file-selection --title="Select yakmesh upgrade package" 2>/dev/null`, { encoding: 'utf8' }).trim();
          } else if (process.platform === 'win32') {
            src = execSync(
              'powershell -NoProfile -Command "Add-Type -AssemblyName System.Windows.Forms; $d=New-Object System.Windows.Forms.OpenFileDialog; $d.Filter=\'Upgrade packages (*.zip;*.tgz)|*.zip;*.tgz|All files|*.*\'; if($d.ShowDialog() -eq \'OK\'){$d.FileName}"',
              { encoding: 'utf8' }).trim();
          } else if (process.platform === 'darwin') {
            src = execSync(`osascript -e 'POSIX path of (choose file with prompt "Select yakmesh upgrade package")'`, { encoding: 'utf8' }).trim();
          }
        } catch { src = null; }
        if (!src) {
          console.log(chalk.red('✗ No package selected. Pass a path: yakmesh upgrade <package.zip|package.tgz>'));
          process.exit(1);
        }
      }
    }

    if (!existsSync(src)) {
      console.log(chalk.red(`✗ Package not found: ${src}`));
      process.exit(1);
    }

    console.log(chalk.yellow('Yakmesh in-place upgrade\n'));
    console.log(chalk.gray(`  Package: ${src}`));
    console.log(chalk.gray(`  Install: ${ROOT}`));
    console.log(chalk.gray('  data/, node_modules/, models/, .git/ are never touched —\n  identity, KARMA, keys, and your setup ride through.\n'));

    // ── Detect a running node + whether it is supervised ──
    let nodeState = null;
    try {
      const res = await fetch(`${API}/api/update`, { signal: AbortSignal.timeout(2000) });
      if (res.ok) nodeState = await res.json();
    } catch { }

    // Build the entry list {name, data} — zip natively, tgz via system tar
    let entries = null;
    let extractDir = null;
    const loadEntries = () => {
      if (entries) return entries;
      if (/\.zip$/i.test(src)) {
        entries = [...zipEntries(readFileSync(src))];
      } else if (/\.(tgz|tar\.gz|tar)$/i.test(src)) {
        extractDir = join(DATA, `upgrade-extract-${Date.now()}`);
        mkdirSync(extractDir, { recursive: true });
        try {
          execSync(`tar -xf "${src}" -C "${extractDir}"`, { stdio: ['ignore', 'pipe', 'pipe'] });
        } catch {
          rmSync(extractDir, { recursive: true, force: true });
          console.log(chalk.red('✗ Could not extract tarball (need system tar/bsdtar)'));
          process.exit(1);
        }
        let base = extractDir;
        if (existsSync(join(base, 'package', 'package.json'))) base = join(base, 'package');
        entries = [...walk(base)].map(({ abs, rel }) => ({ name: rel, data: readFileSync(abs) }));
      } else {
        console.log(chalk.red('✗ Unrecognized package format — expected .zip or .tgz'));
        process.exit(1);
      }
      return entries;
    };
    const cleanup = () => { if (extractDir) { try { rmSync(extractDir, { recursive: true, force: true }); } catch { } } };

    // ══ Path A: node is RUNNING under the supervisor ══
    // Stage through the live API (tgz→zip normalization included), then
    // offer to apply — the node writes the marker and exits; yakmesh-run
    // performs the swap on respawn.
    if (nodeState && nodeState.supervised) {
      console.log(chalk.gray('  Node is running under yakmesh-run — staging via the update API.'));
      const res = await fetch(`${API}/api/update/stage`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/octet-stream' },
        body: readFileSync(src),
      });
      const staged = await res.json().catch(() => ({}));
      if (!res.ok) {
        console.log(chalk.red(`✗ Stage failed: ${staged.error || res.statusText}`));
        process.exit(1);
      }
      console.log(chalk.green(`✓ Staged ${staged.files} files (${(staged.size / 1024 / 1024).toFixed(1)} MB), sha256 ${staged.sha256.slice(0, 16)}…`));
      if (await ask('\nApply now? The node will restart and the supervisor performs the swap.')) {
        const ar = await fetch(`${API}/api/update/apply`, { method: 'POST' }).catch(() => null);
        console.log(chalk.green('✓ Apply signaled — node restarting; supervisor swaps the code.'));
        console.log(chalk.gray('  Watch it come back: tail -f data/supervisor.log\n'));
      } else {
        console.log(chalk.gray('\nStaged only. Apply later via the dashboard Updates card or'));
        console.log(chalk.gray(`  curl -X POST ${API}/api/update/apply\n`));
      }
      return;
    }

    // ══ Path B: node is RUNNING but NOT supervised ══
    // Overlaying code under a live unsupervised process is unsafe — offer
    // to stage for the next yakmesh-run launch, or quit so the user can
    // stop the node and re-run (which then applies in place immediately).
    if (nodeState && !nodeState.supervised) {
      console.log(chalk.yellow('  ⚠ Node is running WITHOUT the supervisor (node server/index.js).'));
      console.log(chalk.gray('    Applying code under a live process is unsafe.\n'));
      const stageOnly = await ask('Stage the package for the next `yakmesh-run` restart instead? (n = quit so you can stop the node and re-run)', true);
      if (stageOnly) {
        const res = await fetch(`${API}/api/update/stage`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/octet-stream' },
          body: readFileSync(src),
        });
        const staged = await res.json().catch(() => ({}));
        if (!res.ok) {
          console.log(chalk.red(`✗ Stage failed: ${staged.error || res.statusText}`));
          process.exit(1);
        }
        console.log(chalk.green(`✓ Staged ${staged.files} files — relaunch via \`node scripts/yakmesh-run.js\` to apply.`));
      } else {
        console.log(chalk.gray('\nStop the node, then re-run `yakmesh upgrade` — it will apply in place.'));
      }
      return;
    }

    // ══ Path C: node NOT running — direct in-place apply ══
    loadEntries();
    if (!entries.length) {
      cleanup();
      console.log(chalk.red('✗ Package contained no applicable files'));
      process.exit(1);
    }
    console.log(chalk.gray(`  ${entries.length} package entries\n`));

    if (options.dryRun) {
      for (const { name } of entries) {
        const top = name.replace(/\\/g, '/').split('/')[0];
        console.log(chalk.gray(`    ${EXCLUDE_DIRS.has(top) ? 'skip' : ' →  '} ${name}`));
      }
      console.log(chalk.cyan('\nDry run — nothing applied.'));
      cleanup();
      return;
    }

    const { overlaid, added, quarantined, rollbackDir } = applyUpgradePackage(entries, {
      root: ROOT,
      dataDir: DATA,
      log: (m) => console.log(chalk.gray(`  ${m}`)),
    });
    cleanup();

    console.log(chalk.green(`\n✓ Applied: ${overlaid} files overlaid`));
    if (added.length) console.log(chalk.green(`✓ Added: ${added.length} new files`));
    if (quarantined) console.log(chalk.yellow(`⚠ Quarantined: ${quarantined} leftover file(s) not in new manifest`));
    if (rollbackDir) console.log(chalk.gray(`  Rollback: ${rollbackDir}`));

    // Requirements met — offer to launch under the supervisor so the node
    // (and its update machinery) runs in the designed mode.
    if (await ask('\nStart yakmesh under the supervisor now?', true)) {
      const child = spawn(process.execPath, [join(ROOT, 'scripts', 'yakmesh-run.js')], {
        cwd: ROOT, detached: true, stdio: 'ignore',
      });
      child.unref();
      console.log(chalk.green('✓ yakmesh-run launched in the background — logs: data/supervisor.log\n'));
    } else {
      console.log(chalk.gray('\nStart when ready: node scripts/yakmesh-run.js\n'));
    }
  });

// ===== START COMMAND =====
program
  .command('start')
  .description('Start the Yakmesh Node')
  .option('-c, --config <path>', 'Path to config file', './yakmesh.config.js')
  .option('-d, --daemon', 'Run as background daemon')
  .action(async (options) => {
    showBanner();
    
    const configPath = resolve(options.config);
    
    if (!existsSync(configPath)) {
      console.log(chalk.red('✗ Error: yakmesh.config.js not found'));
      console.log(chalk.gray('  Run: npx yakmesh init'));
      process.exit(1);
    }

    console.log(chalk.yellow('Starting Yakmesh Node...\n'));

    // Dynamic import of server - use the package's server module
    const serverPath = join(__dirname, '..', 'server', 'index.js');
    const serverURL = new URL(`file:///${serverPath.replace(/\\/g, '/')}`);
    const { YakmeshNode } = await import(serverURL.href);
    
    // Load config from current working directory
    const configURL = new URL(`file:///${configPath.replace(/\\/g, '/')}`);
    const { default: config } = await import(configURL.href);

    const node = new YakmeshNode(config);

    // Handle shutdown
    process.on('SIGINT', async () => {
      console.log(chalk.yellow('\n\nShutting down...'));
      await node.stop();
      process.exit(0);
    });

    process.on('SIGTERM', async () => {
      await node.stop();
      process.exit(0);
    });

    await node.start();
  });

// ===== STATUS COMMAND =====
program
  .command('status')
  .description('Show node status')
  .option('-p, --port <port>', 'HTTP port of local node', '3080')
  .action(async (options) => {
    try {
      const response = await fetch(`http://localhost:${options.port}/health`);
      const data = await response.json();

      showBanner();
      console.log(chalk.green('✓ Node is running\n'));
      console.log(chalk.cyan('📊 Status:'));
      console.log(chalk.gray(`   Node ID:    ${data.nodeId}`));
      console.log(chalk.gray(`   Peers:      ${data.peers}`));
      console.log(chalk.gray(`   Algorithm:  ${data.algorithm}`));
      console.log('');
    } catch (e) {
      console.log(chalk.red('✗ Node is not running'));
      console.log(chalk.gray(`  Could not connect to http://localhost:${options.port}`));
      process.exit(1);
    }
  });

// ===== PEERS COMMAND =====
program
  .command('peers')
  .description('List connected peers')
  .option('-p, --port <port>', 'HTTP port of local node', '3080')
  .action(async (options) => {
    try {
      const response = await fetch(`http://localhost:${options.port}/peers`);
      const peers = await response.json();

      showBanner();
      
      if (peers.length === 0) {
        console.log(chalk.yellow('No peers connected\n'));
        return;
      }

      console.log(chalk.cyan(`📡 Connected Peers (${peers.length}):\n`));
      
      for (const peer of peers) {
        const ago = Math.floor((Date.now() - peer.lastSeen) / 1000);
        console.log(chalk.white(`  ${peer.name}`));
        console.log(chalk.gray(`    ID:        ${peer.nodeId.slice(0, 24)}...`));
        console.log(chalk.gray(`    Endpoint:  ${peer.endpoint || 'inbound'}`));
        console.log(chalk.gray(`    Last seen: ${ago}s ago`));
        console.log('');
      }
    } catch (e) {
      console.log(chalk.red('✗ Could not fetch peers'));
      console.log(chalk.gray(`  Is the node running on port ${options.port}?`));
      process.exit(1);
    }
  });

// ===== INFO COMMAND =====
program
  .command('info')
  .description('Show detailed node information')
  .option('-p, --port <port>', 'HTTP port of local node', '3080')
  .action(async (options) => {
    try {
      const [nodeRes, replRes] = await Promise.all([
        fetch(`http://localhost:${options.port}/node`),
        fetch(`http://localhost:${options.port}/replication`),
      ]);
      
      const node = await nodeRes.json();
      const repl = await replRes.json();

      showBanner();
      console.log(chalk.cyan('🦬 Node Information:\n'));
      
      console.log(chalk.white('  Identity:'));
      console.log(chalk.gray(`    Node ID:      ${node.nodeId}`));
      console.log(chalk.gray(`    Name:         ${node.name}`));
      console.log(chalk.gray(`    Region:       ${node.region}`));
      console.log(chalk.gray(`    Algorithm:    ${node.algorithm} (NIST Level ${node.nistLevel})`));
      console.log(chalk.gray(`    Created:      ${new Date(node.createdAt).toISOString()}`));
      
      console.log(chalk.white('\n  Capabilities:'));
      for (const cap of node.capabilities) {
        console.log(chalk.gray(`    • ${cap}`));
      }
      
      console.log(chalk.white('\n  Replication:'));
      console.log(chalk.gray(`    Log entries:  ${repl.replicationLogSize}`));
      console.log(chalk.gray(`    Peer states:  ${repl.peerStates.length}`));
      console.log(chalk.gray(`    Tables:       ${repl.replicatedTables.join(', ')}`));
      
      console.log(chalk.white('\n  Public Key (ML-DSA-65):'));
      console.log(chalk.gray(`    ${node.publicKey.slice(0, 64)}...`));
      console.log('');
    } catch (e) {
      console.log(chalk.red('✗ Could not fetch node info'));
      process.exit(1);
    }
  });

// ===== JOIN COMMAND =====
program
  .command('join <endpoint>')
  .description('Connect to a peer node')
  .option('-p, --port <port>', 'HTTP port of local node', '3080')
  .action(async (endpoint, options) => {
    try {
      const response = await fetch(`http://localhost:${options.port}/connect`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ endpoint }),
      });
      
      const result = await response.json();
      
      if (result.success) {
        console.log(chalk.green(`✓ Connected to ${endpoint}`));
      } else {
        console.log(chalk.red(`✗ Failed to connect: ${result.error}`));
      }
    } catch (e) {
      console.log(chalk.red('✗ Could not connect'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

// ===== OPEN COMMAND =====
// Quick access to node interfaces
program
  .command('open [target]')
  .description('Open node interfaces in browser (dashboard, docs, health, or yak:// URL)')
  .option('-p, --port <port>', 'HTTP port of local node', '3080')
  .action(async (target = 'dashboard', options) => {
    const port = parseInt(options.port);
    
    // Built-in targets
    const targets = {
      'dashboard': `http://localhost:${port}/dashboard`,
      'dash': `http://localhost:${port}/dashboard`,
      'd': `http://localhost:${port}/dashboard`,
      'docs': `http://localhost:${port}/docs/`,
      'documentation': `http://localhost:${port}/docs/`,
      'health': `http://localhost:${port}/health`,
      'h': `http://localhost:${port}/health`,
      'peers': `http://localhost:${port}/peers`,
      'metrics': `http://localhost:${port}/metrics`,
    };
    
    let url;
    
    if (target.startsWith('yak://')) {
      // Handle yak:// URLs
      try {
        const { yakToHttp } = await import('../protocol/yak-protocol.js');
        url = yakToHttp(target, port);
      } catch (e) {
        console.log(chalk.red(`✗ Invalid yak:// URL: ${e.message}`));
        process.exit(1);
      }
    } else if (targets[target.toLowerCase()]) {
      url = targets[target.toLowerCase()];
    } else {
      // Try it as a yak:// URL without prefix
      try {
        const { yakToHttp } = await import('../protocol/yak-protocol.js');
        url = yakToHttp(`yak://${target}`, port);
      } catch (e) {
        console.log(chalk.yellow(`Unknown target: ${target}`));
        console.log(chalk.gray('\nAvailable targets:'));
        console.log(chalk.gray('  dashboard (d)  - Node dashboard'));
        console.log(chalk.gray('  docs           - Documentation'));
        console.log(chalk.gray('  health (h)     - Health check'));
        console.log(chalk.gray('  peers          - Peer list'));
        console.log(chalk.gray('  metrics        - Node metrics'));
        console.log(chalk.gray('  yak://<url>    - Any yak:// URL'));
        process.exit(1);
      }
    }
    
    console.log(chalk.cyan(`\n🌐 Opening: ${url}\n`));
    
    // Open in default browser
    const { exec } = await import('child_process');
    const { platform } = await import('os');
    
    const os = platform();
    let openCmd;
    
    if (os === 'win32') {
      // Windows: start requires empty title when URL has special chars
      openCmd = `start "" "${url}"`;
    } else if (os === 'darwin') {
      openCmd = `open "${url}"`;
    } else {
      openCmd = `xdg-open "${url}"`;
    }
    
    exec(openCmd, (err) => {
      if (err) {
        console.log(chalk.red('✗ Could not open browser'));
        console.log(chalk.gray(`  ${err.message}`));
      }
    });
  });

// ===== PROTOCOL COMMAND GROUP =====
const protocolCmd = program
  .command('protocol')
  .description('Manage yak:// protocol registration');

protocolCmd
  .command('register')
  .description('Register yak:// protocol with the operating system')
  .option('-p, --port <port>', 'HTTP port of local node', '3080')
  .action(async (options) => {
    showBanner();
    console.log(chalk.yellow('Registering yak:// protocol...\n'));
    
    try {
      const { YakProtocolHandler } = await import('../protocol/yak-protocol.js');
      const handler = new YakProtocolHandler({ port: parseInt(options.port) });
      
      const success = await handler.register();
      
      if (success) {
        console.log(chalk.green('\n✓ yak:// protocol registered successfully!\n'));
        console.log(chalk.cyan('Try these URLs:'));
        console.log(chalk.gray('  yak://dashboard   - Node dashboard'));
        console.log(chalk.gray('  yak://site        - Hosted website'));
        console.log(chalk.gray('  yak://peers       - Connected peers'));
        console.log(chalk.gray('  yak://content/<hash> - Content by hash'));
        console.log('');
      } else {
        console.log(chalk.red('✗ Failed to register protocol'));
        process.exit(1);
      }
    } catch (e) {
      console.log(chalk.red('✗ Error registering protocol'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

protocolCmd
  .command('unregister')
  .description('Unregister yak:// protocol from the operating system')
  .action(async () => {
    showBanner();
    console.log(chalk.yellow('Unregistering yak:// protocol...\n'));
    
    try {
      const { YakProtocolHandler } = await import('../protocol/yak-protocol.js');
      const handler = new YakProtocolHandler();
      
      await handler.unregister();
      console.log(chalk.green('✓ yak:// protocol unregistered'));
    } catch (e) {
      console.log(chalk.red('✗ Error unregistering protocol'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

protocolCmd
  .command('test <url>')
  .description('Test a yak:// URL without opening browser')
  .option('-p, --port <port>', 'HTTP port of local node', '3080')
  .action(async (url, options) => {
    try {
      const { parseYakUrl, yakToHttp } = await import('../protocol/yak-protocol.js');
      
      const parsed = parseYakUrl(url);
      const httpUrl = yakToHttp(url, parseInt(options.port));
      
      console.log(chalk.cyan('\n🔗 YAK:// Protocol Test\n'));
      console.log(chalk.white('Input:'));
      console.log(chalk.gray(`  ${url}\n`));
      console.log(chalk.white('Parsed:'));
      console.log(chalk.gray(`  Type:   ${parsed.type}`));
      console.log(chalk.gray(`  Route:  ${parsed.route || parsed.hash || parsed.name || '-'}`));
      console.log(chalk.gray(`  Path:   ${parsed.path}\n`));
      console.log(chalk.white('HTTP URL:'));
      console.log(chalk.green(`  ${httpUrl}`));
      console.log('');
    } catch (e) {
      console.log(chalk.red('✗ Error parsing URL'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

protocolCmd
  .command('open <url>')
  .description('Open a yak:// URL in the default browser')
  .option('-p, --port <port>', 'HTTP port of local node', '3080')
  .action(async (url, options) => {
    try {
      const { YakProtocolHandler } = await import('../protocol/yak-protocol.js');
      const handler = new YakProtocolHandler({ port: parseInt(options.port) });
      
      console.log(chalk.cyan(`\n🔗 Opening: ${url}\n`));
      await handler.handle(url);
    } catch (e) {
      console.log(chalk.red('✗ Error opening URL'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

// ===== BOOKMARK SUBCOMMANDS =====
const bookmarkCmd = protocolCmd
  .command('bookmark')
  .alias('bm')
  .description('Manage yak:// URL bookmarks (local pet names)');

bookmarkCmd
  .command('add <name> <target>')
  .description('Add a bookmark (e.g., yakmesh protocol bookmark add alice yak://content/abc123)')
  .action(async (name, target) => {
    try {
      const { getBookmarkManager } = await import('../protocol/yak-protocol.js');
      const bookmarks = getBookmarkManager();
      
      // Handle yak:// prefix in target
      if (target.startsWith('yak://')) {
        target = target.replace(/^yak:\/\//i, '');
      }
      
      const success = bookmarks.add(name, target);
      
      if (success) {
        console.log(chalk.green(`\n✓ Bookmark added: yak://${name.toLowerCase()} → ${bookmarks.get(name.toLowerCase())}\n`));
        console.log(chalk.cyan('Usage:'));
        console.log(chalk.gray(`  yakmesh protocol open yak://${name.toLowerCase()}`));
        console.log(chalk.gray(`  yakmesh protocol test yak://${name.toLowerCase()}`));
      } else {
        console.log(chalk.yellow(`\n⚠ Could not add bookmark '${name}' - it may be a builtin route\n`));
      }
      console.log('');
    } catch (e) {
      console.log(chalk.red('✗ Error adding bookmark'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

bookmarkCmd
  .command('remove <name>')
  .alias('rm')
  .description('Remove a bookmark')
  .action(async (name) => {
    try {
      const { getBookmarkManager } = await import('../protocol/yak-protocol.js');
      const bookmarks = getBookmarkManager();
      
      if (!bookmarks.has(name)) {
        console.log(chalk.yellow(`\n⚠ Bookmark '${name}' not found\n`));
        process.exit(1);
      }
      
      bookmarks.remove(name);
      console.log(chalk.green(`\n✓ Bookmark '${name}' removed\n`));
    } catch (e) {
      console.log(chalk.red('✗ Error removing bookmark'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

bookmarkCmd
  .command('list')
  .alias('ls')
  .description('List all bookmarks')
  .action(async () => {
    try {
      const { getBookmarkManager } = await import('../protocol/yak-protocol.js');
      const bookmarks = getBookmarkManager();
      
      const all = bookmarks.list();
      const names = Object.keys(all);
      
      console.log(chalk.cyan('\n📖 YAK:// Bookmarks\n'));
      
      if (names.length === 0) {
        console.log(chalk.gray('  No bookmarks yet.'));
        console.log(chalk.gray('  Add one with: yakmesh protocol bookmark add <name> <target>'));
      } else {
        for (const name of names.sort()) {
          const bm = all[name];
          console.log(chalk.white(`  yak://${name}`));
          console.log(chalk.gray(`    → ${bm.target}`));
        }
        console.log(chalk.gray(`\n  Total: ${names.length} bookmark(s)`));
      }
      console.log('');
    } catch (e) {
      console.log(chalk.red('✗ Error listing bookmarks'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

bookmarkCmd
  .command('get <name>')
  .description('Get details of a specific bookmark')
  .action(async (name) => {
    try {
      const { getBookmarkManager, yakToHttp } = await import('../protocol/yak-protocol.js');
      const bookmarks = getBookmarkManager();
      
      const target = bookmarks.get(name);
      
      if (!target) {
        console.log(chalk.yellow(`\n⚠ Bookmark '${name}' not found\n`));
        process.exit(1);
      }
      
      const all = bookmarks.list();
      const bm = all[name.toLowerCase()];
      
      console.log(chalk.cyan(`\n📖 Bookmark: ${name}\n`));
      console.log(chalk.white('Details:'));
      console.log(chalk.gray(`  URL:     yak://${name.toLowerCase()}`));
      console.log(chalk.gray(`  Target:  ${target}`));
      console.log(chalk.gray(`  HTTP:    ${yakToHttp('yak:/' + target)}`));
      if (bm?.createdAt) {
        console.log(chalk.gray(`  Created: ${new Date(bm.createdAt).toLocaleString()}`));
      }
      console.log('');
    } catch (e) {
      console.log(chalk.red('✗ Error getting bookmark'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

// ===== GEO COMMAND GROUP =====
const geoCmd = program
  .command('geo')
  .description('Geographic proof and exclusion zone management');

geoCmd
  .command('status')
  .description('Show geographic proof status and statistics')
  .option('-p, --port <port>', 'HTTP port of local node', '3080')
  .action(async (options) => {
    try {
      const response = await fetch(`http://localhost:${options.port}/geo/status`);
      const data = await response.json();

      showBanner();
      console.log(chalk.cyan('🌍 Geographic Proof Status\n'));
      
      console.log(chalk.white('  Time Source:'));
      console.log(chalk.gray(`    Type:       ${data.timeSource?.type || 'UNKNOWN'}`));
      console.log(chalk.gray(`    Quality:    ${data.timeSource?.quality || 'N/A'}`));
      console.log(chalk.gray(`    Precision:  ${data.timeSource?.precision || 'N/A'}`));
      
      console.log(chalk.white('\n  Landmarks:'));
      console.log(chalk.gray(`    Registered: ${data.landmarks?.count || 0}`));
      console.log(chalk.gray(`    Verified:   ${data.landmarks?.verified || 0}`));
      
      console.log(chalk.white('\n  Exclusion Zones:'));
      console.log(chalk.gray(`    Active:     ${data.zones?.active || 0}`));
      console.log(chalk.gray(`    Total:      ${data.zones?.total || 0}`));
      
      console.log(chalk.white('\n  My Geographic Proof:'));
      if (data.myProof) {
        console.log(chalk.gray(`    Confidence: ${(data.myProof.confidence * 100).toFixed(1)}%`));
        console.log(chalk.gray(`    Zones:      ${data.myProof.zoneCount} exclusion zones`));
        console.log(chalk.gray(`    Last RTT:   ${data.myProof.lastRttMs?.toFixed(2) || 'N/A'} ms`));
      } else {
        console.log(chalk.yellow('    No geographic proof established yet'));
        console.log(chalk.gray('    Run: yakmesh geo prove'));
      }
      console.log('');
    } catch (e) {
      console.log(chalk.red('✗ Could not fetch geo status'));
      console.log(chalk.gray(`  Is the node running on port ${options.port}?`));
      process.exit(1);
    }
  });

geoCmd
  .command('landmarks')
  .description('List known geographic landmarks')
  .option('-p, --port <port>', 'HTTP port of local node', '3080')
  .option('-v, --verified', 'Show only verified landmarks')
  .action(async (options) => {
    try {
      const url = options.verified 
        ? `http://localhost:${options.port}/geo/landmarks?verified=true`
        : `http://localhost:${options.port}/geo/landmarks`;
      const response = await fetch(url);
      const data = await response.json();

      showBanner();
      console.log(chalk.cyan('📍 Geographic Landmarks\n'));
      
      if (!data.landmarks || data.landmarks.length === 0) {
        console.log(chalk.yellow('  No landmarks registered\n'));
        console.log(chalk.gray('  Landmarks are discovered via KHATA gossip'));
        console.log(chalk.gray('  or can be added with: yakmesh geo add-landmark'));
        return;
      }

      for (const lm of data.landmarks) {
        const verifiedIcon = lm.verified ? chalk.green('✓') : chalk.gray('○');
        console.log(chalk.white(`  ${verifiedIcon} ${lm.name}`));
        console.log(chalk.gray(`      ID:       ${lm.nodeId.slice(0, 24)}...`));
        console.log(chalk.gray(`      Location: ${lm.lat?.toFixed(4)}°, ${lm.lon?.toFixed(4)}°`));
        console.log(chalk.gray(`      Tier:     ${lm.tier || 'UNKNOWN'}`));
        if (lm.lastRttMs) {
          const distance = (lm.lastRttMs / 2) * 199861.639 / 1000;
          console.log(chalk.gray(`      RTT:      ${lm.lastRttMs.toFixed(2)} ms (≥${distance.toFixed(0)} km)`));
        }
        console.log('');
      }
      
      console.log(chalk.gray(`  Total: ${data.landmarks.length} landmark(s)`));
      console.log('');
    } catch (e) {
      console.log(chalk.red('✗ Could not fetch landmarks'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

geoCmd
  .command('zones')
  .description('List exclusion zones for this node')
  .option('-p, --port <port>', 'HTTP port of local node', '3080')
  .action(async (options) => {
    try {
      const response = await fetch(`http://localhost:${options.port}/geo/zones`);
      const data = await response.json();

      showBanner();
      console.log(chalk.cyan('🚫 Geographic Exclusion Zones\n'));
      console.log(chalk.gray('  Exclusion zones prove where this node CANNOT be.\n'));
      
      if (!data.zones || data.zones.length === 0) {
        console.log(chalk.yellow('  No exclusion zones established\n'));
        console.log(chalk.gray('  Run: yakmesh geo prove'));
        return;
      }

      for (const zone of data.zones) {
        console.log(chalk.white(`  Zone: ${zone.landmarkName || zone.landmarkId.slice(0, 16)}...`));
        console.log(chalk.gray(`      Landmark:  ${zone.lat?.toFixed(4)}°, ${zone.lon?.toFixed(4)}°`));
        console.log(chalk.gray(`      Radius:    ${zone.radiusKm.toFixed(1)} km (min distance)`));
        console.log(chalk.gray(`      RTT:       ${zone.rttMs.toFixed(2)} ms`));
        console.log(chalk.gray(`      Measured:  ${new Date(zone.measuredAt).toISOString()}`));
        console.log('');
      }
      
      console.log(chalk.gray(`  Total: ${data.zones.length} exclusion zone(s)`));
      console.log('');
    } catch (e) {
      console.log(chalk.red('✗ Could not fetch zones'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

geoCmd
  .command('prove')
  .description('Generate a new geographic proof')
  .option('-p, --port <port>', 'HTTP port of local node', '3080')
  .option('-f, --force', 'Force re-measurement of all landmarks')
  .action(async (options) => {
    try {
      showBanner();
      console.log(chalk.yellow('🌍 Generating Geographic Proof...\n'));
      console.log(chalk.gray('  Measuring RTT to known landmarks...\n'));
      
      const response = await fetch(`http://localhost:${options.port}/geo/prove`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ force: options.force || false }),
      });
      
      const result = await response.json();
      
      if (result.success) {
        console.log(chalk.green('✓ Geographic proof generated!\n'));
        console.log(chalk.white('  Results:'));
        console.log(chalk.gray(`    Confidence:      ${(result.proof.confidence * 100).toFixed(1)}%`));
        console.log(chalk.gray(`    Exclusion zones: ${result.proof.zoneCount}`));
        console.log(chalk.gray(`    Time source:     ${result.proof.timeSource}`));
        console.log(chalk.gray(`    Valid until:     ${new Date(result.proof.expiresAt).toISOString()}`));
        
        if (result.proof.zones && result.proof.zones.length > 0) {
          console.log(chalk.white('\n  Zones created:'));
          for (const zone of result.proof.zones.slice(0, 5)) {
            console.log(chalk.gray(`    • ${zone.landmarkName}: ≥${zone.radiusKm.toFixed(1)} km away`));
          }
          if (result.proof.zones.length > 5) {
            console.log(chalk.gray(`    ... and ${result.proof.zones.length - 5} more`));
          }
        }
      } else {
        console.log(chalk.red(`✗ Failed to generate proof: ${result.error}`));
        if (result.reason) {
          console.log(chalk.gray(`  ${result.reason}`));
        }
      }
      console.log('');
    } catch (e) {
      console.log(chalk.red('✗ Could not generate proof'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

geoCmd
  .command('verify <nodeId>')
  .description('Verify geographic claims of another node')
  .option('-p, --port <port>', 'HTTP port of local node', '3080')
  .action(async (nodeId, options) => {
    try {
      showBanner();
      console.log(chalk.yellow(`🔍 Verifying node ${nodeId.slice(0, 24)}...\n`));
      
      const response = await fetch(`http://localhost:${options.port}/geo/verify`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ nodeId }),
      });
      
      const result = await response.json();
      
      if (result.verified) {
        console.log(chalk.green('✓ Geographic claims verified!\n'));
        console.log(chalk.white('  Verification Results:'));
        console.log(chalk.gray(`    Node ID:     ${result.nodeId.slice(0, 32)}...`));
        console.log(chalk.gray(`    Zones valid: ${result.validZones}/${result.totalZones}`));
        console.log(chalk.gray(`    Confidence:  ${(result.confidence * 100).toFixed(1)}%`));
        
        if (result.region) {
          console.log(chalk.gray(`    Region:      ${result.region}`));
        }
      } else {
        console.log(chalk.red('✗ Geographic verification failed\n'));
        console.log(chalk.gray(`  Reason: ${result.reason || 'Unknown'}`));
        
        if (result.violations && result.violations.length > 0) {
          console.log(chalk.white('\n  Violations:'));
          for (const v of result.violations) {
            console.log(chalk.red(`    • ${v}`));
          }
        }
      }
      console.log('');
    } catch (e) {
      console.log(chalk.red('✗ Could not verify node'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

geoCmd
  .command('add-landmark <name>')
  .description('Add a well-known landmark node')
  .option('-p, --port <port>', 'HTTP port of local node', '3080')
  .option('--lat <latitude>', 'Latitude of landmark')
  .option('--lon <longitude>', 'Longitude of landmark')
  .option('--node-id <nodeId>', 'Node ID of landmark')
  .option('--endpoint <url>', 'WebSocket endpoint of landmark')
  .action(async (name, options) => {
    try {
      if (!options.lat || !options.lon) {
        console.log(chalk.red('✗ Error: --lat and --lon are required'));
        console.log(chalk.gray('  Example: yakmesh geo add-landmark "NYC Beacon" --lat 40.7128 --lon -74.0060 --endpoint ws://beacon.nyc:9001'));
        process.exit(1);
      }
      
      const response = await fetch(`http://localhost:${options.port}/geo/landmarks`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name,
          lat: parseFloat(options.lat),
          lon: parseFloat(options.lon),
          nodeId: options.nodeId,
          endpoint: options.endpoint,
        }),
      });
      
      const result = await response.json();
      
      if (result.success) {
        console.log(chalk.green(`\n✓ Landmark '${name}' added\n`));
        console.log(chalk.gray(`  Location: ${options.lat}°, ${options.lon}°`));
        if (options.endpoint) {
          console.log(chalk.gray(`  Endpoint: ${options.endpoint}`));
        }
      } else {
        console.log(chalk.red(`✗ Failed to add landmark: ${result.error}`));
      }
      console.log('');
    } catch (e) {
      console.log(chalk.red('✗ Could not add landmark'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

geoCmd
  .command('physics')
  .description('Show speed-of-light physics constants used for verification')
  .action(async () => {
    showBanner();
    console.log(chalk.cyan('⚡ Speed-of-Light Physics Constants\n'));
    
    console.log(chalk.white('  Fundamental Constants:'));
    console.log(chalk.gray('    Speed of light (vacuum): 299,792.458 km/s'));
    console.log(chalk.gray('    Speed in fiber (0.67c):  199,861.639 km/s'));
    
    console.log(chalk.white('\n  Example RTT to Distance:'));
    const examples = [1, 5, 10, 50, 100, 200];
    for (const rtt of examples) {
      const distance = (rtt / 2) * 199861.639 / 1000;
      console.log(chalk.gray(`    ${rtt.toString().padStart(3)} ms RTT → ≥${distance.toFixed(0).padStart(5)} km minimum distance`));
    }
    
    console.log(chalk.white('\n  How It Works:'));
    console.log(chalk.gray('    1. Measure RTT to landmark with known location'));
    console.log(chalk.gray('    2. Calculate minimum distance using speed of light'));
    console.log(chalk.gray('    3. Create exclusion zone (node CANNOT be within radius)'));
    console.log(chalk.gray('    4. Network latency only adds delay → zones are always valid'));
    
    console.log(chalk.white('\n  Key Insight:'));
    console.log(chalk.cyan('    "We prove where you CANNOT be, not where you ARE"'));
    console.log(chalk.gray('    Physics only provides lower bound on distance.'));
    console.log(chalk.gray('    This is unforgeable - speed of light cannot be exceeded.'));
    console.log('');
  });

// ===== DOCS COMMAND GROUP =====
const docsCmd = program
  .command('docs')
  .description('Embedded documentation management');

// docs info - Show bundle information
docsCmd
  .command('info')
  .description('Show documentation bundle information')
  .action(async () => {
    try {
      const { getBundleInfo, BUNDLE_HASH, BUNDLE_VERSION } = await import('../embedded-docs/index.js');
      const info = getBundleInfo();
      
      console.log(chalk.cyan('\n📦 YAKMESH Embedded Documentation Bundle\n'));
      console.log(chalk.white('  Bundle Hash:'), chalk.yellow(BUNDLE_HASH));
      console.log(chalk.white('  Version:    '), chalk.green(BUNDLE_VERSION));
      console.log(chalk.white('  Files:      '), info.fileCount);
      console.log(chalk.white('  Total Size: '), Math.round(info.totalSize / 1024) + ' KB');
      console.log('');
      console.log(chalk.gray('  Run "yakmesh docs verify" to verify bundle integrity.'));
      console.log(chalk.gray('  Run "yakmesh docs list" to see all files.'));
      console.log('');
    } catch (err) {
      console.error(chalk.red('✗ Error loading docs bundle:'), err.message);
      process.exit(1);
    }
  });

// docs verify - Verify bundle integrity
docsCmd
  .command('verify')
  .description('Verify documentation bundle integrity using SHA3-256')
  .option('-v, --verbose', 'Show individual file verification results')
  .action(async (options) => {
    try {
      const { getBundleInfo, getDocsFile, verifyFile, BUNDLE_HASH } = await import('../embedded-docs/index.js');
      const info = getBundleInfo();
      
      console.log(chalk.cyan('\n🔐 Verifying Documentation Bundle...\n'));
      
      let verified = 0;
      let failed = 0;
      
      for (const filePath of info.files) {
        const file = getDocsFile(filePath);
        if (!file) {
          if (options.verbose) {
            console.log(chalk.red('  ✗'), filePath, chalk.gray('- FILE MISSING'));
          }
          failed++;
          continue;
        }
        
        const result = verifyFile(filePath, file.content);
        if (result.valid) {
          verified++;
          if (options.verbose) {
            console.log(chalk.green('  ✓'), filePath, chalk.gray(`(${file.content.length} bytes)`));
          }
        } else {
          failed++;
          if (options.verbose) {
            console.log(chalk.red('  ✗'), filePath, chalk.gray('- HASH MISMATCH'));
          }
        }
      }
      
      console.log('');
      if (failed === 0) {
        console.log(chalk.green('✓ Bundle verification PASSED'));
        console.log(chalk.gray(`  ${verified} files verified`));
        console.log(chalk.gray(`  Bundle: ${BUNDLE_HASH.substring(0, 32)}...`));
      } else {
        console.log(chalk.red('✗ Bundle verification FAILED'));
        console.log(chalk.gray(`  ${verified} passed, ${failed} failed`));
        process.exit(1);
      }
      console.log('');
    } catch (err) {
      console.error(chalk.red('✗ Error:'), err.message);
      process.exit(1);
    }
  });

// docs list - List all files in bundle
docsCmd
  .command('list')
  .description('List all files in the documentation bundle')
  .option('--html', 'Show only HTML files')
  .option('--json', 'Output as JSON')
  .action(async (options) => {
    try {
      const { getBundleInfo, FILE_INDEX } = await import('../embedded-docs/index.js');
      const info = getBundleInfo();
      
      let files = info.files;
      if (options.html) {
        files = files.filter(f => f.endsWith('.html'));
      }
      
      if (options.json) {
        console.log(JSON.stringify({ files, count: files.length }, null, 2));
        return;
      }
      
      console.log(chalk.cyan(`\n📄 Documentation Files (${files.length})\n`));
      for (const file of files.sort()) {
        const meta = FILE_INDEX[file];
        const size = meta ? Math.round(meta.size / 1024) + ' KB' : '?';
        console.log(chalk.gray('  -'), file, chalk.gray(`(${size})`));
      }
      console.log('');
    } catch (err) {
      console.error(chalk.red('✗ Error:'), err.message);
      process.exit(1);
    }
  });

// docs serve - Start documentation server
docsCmd
  .command('serve')
  .description('Start a local documentation server')
  .option('-p, --port <port>', 'Port to serve on', '8080')
  .action(async (options) => {
    try {
      const express = (await import('express')).default;
      const { serveDocsFile, getBundleInfo, BUNDLE_HASH } = await import('../embedded-docs/index.js');
      
      const app = express();
      const port = parseInt(options.port);
      
      // Order matters! Specific routes first to avoid redirect loops
      app.get('/docs/_bundle', (req, res) => res.json(getBundleInfo()));
      app.get('/docs/index.html', (req, res) => serveDocsFile('index.html', res));
      app.get('/docs/', (req, res) => serveDocsFile('index.html', res));
      app.get('/docs', (req, res) => res.redirect('/docs/'));
      app.get('/docs/:file', (req, res) => {
        const file = req.params.file || 'index.html';
        serveDocsFile(file, res);
      });
      
      // Serve assets (silhouettes, etc.) - CSS references ../assets/ from /docs/
      app.get('/assets/*', (req, res) => {
        const assetPath = req.path.substring(1); // Remove leading /
        serveDocsFile(assetPath, res);
      });
      
      app.get('/', (req, res) => res.redirect('/docs/'));
      
      app.listen(port, '0.0.0.0', () => {
        console.log(chalk.cyan('\n📦 YAKMESH Documentation Server\n'));
        console.log(chalk.white('  URL:        '), chalk.green(`http://localhost:${port}/docs/`));
        console.log(chalk.white('  Bundle:     '), chalk.gray(BUNDLE_HASH.substring(0, 24) + '...'));
        console.log(chalk.white('  Files:      '), getBundleInfo().fileCount);
        console.log('');
        console.log(chalk.gray('  Press Ctrl+C to stop.'));
        console.log('');
      });
    } catch (err) {
      console.error(chalk.red('✗ Error:'), err.message);
      process.exit(1);
    }
  });

// docs rebuild - Rebuild the bundle (for developers)
docsCmd
  .command('rebuild')
  .description('Rebuild documentation bundle (development only)')
  .action(async () => {
    console.log(chalk.cyan('\n📦 Rebuilding Documentation Bundle...\n'));
    console.log(chalk.gray('  Run this command from the yakmesh-node directory:'));
    console.log(chalk.white('  npm run build:docs'));
    console.log('');
  });

// ===== VERSION =====
program
  .version(VERSION)
  .description('Yakmesh Network - Post-Quantum Decentralized Node');

// Parse arguments
program.parse();

// Show help if no command
if (!process.argv.slice(2).length) {
  showBanner();
  program.outputHelp();
}



