#!/usr/bin/env node

/**
 * Yakmesh CLI
 * Command-line interface for managing Yakmesh nodes
 */

import { Command } from 'commander';
import chalk from 'chalk';
import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'fs';
import { join, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const VERSION = '2.1.0';

const program = new Command();

// Banner
function showBanner() {
  console.log(chalk.cyan(`
  🦬 Yakmesh Network v${VERSION}
  Post-Quantum Secure • Decentralized • Federated
  `));
}

// ===== INIT COMMAND =====
program
  .command('init')
  .description('Initialize a new Yakmesh Node in the current directory')
  .option('-n, --name <name>', 'Node name', 'My Yakmesh Node')
  .option('-r, --region <region>', 'Geographic region', 'local')
  .option('-p, --port <port>', 'HTTP port', '3000')
  .option('-w, --ws-port <port>', 'WebSocket port', '9001')
  .option('--bootstrap <urls>', 'Comma-separated bootstrap node URLs')
  .action(async (options) => {
    showBanner();
    console.log(chalk.yellow('Initializing new Yakmesh Node...\n'));

    const dataDir = resolve('./data');
    const configPath = resolve('./yakmesh.config.js');

    // Check if already initialized
    if (existsSync(configPath)) {
      console.log(chalk.red('✗ Error: yakmesh.config.js already exists'));
      console.log(chalk.gray('  Use --force to reinitialize'));
      process.exit(1);
    }

    // Create data directory
    if (!existsSync(dataDir)) {
      mkdirSync(dataDir, { recursive: true });
      console.log(chalk.green('✓ Created data directory'));
    }

    // Parse bootstrap nodes
    const bootstrapNodes = options.bootstrap 
      ? options.bootstrap.split(',').map(s => s.trim())
      : [];  // Empty by default - YAKMESH is decentralized, no central bootstrap

    // Generate config
    const config = `/**
 * Yakmesh Node Configuration
 * Generated by: npx yakmesh init
 */
export default {
  // Node identity
  node: {
    name: '${options.name}',
    region: '${options.region}',
    capabilities: ['listings', 'chat', 'forum', 'qcoa'],
  },
  
  // Network settings
  network: {
    httpPort: ${options.port},
    wsPort: ${options.wsPort},
    publicHost: 'localhost',
  },
  
  // Bootstrap nodes (well-known entry points)
  bootstrap: ${JSON.stringify(bootstrapNodes, null, 4).replace(/\n/g, '\n  ')},
  
  // Database
  database: {
    path: './data/peerquanta.db',
    replication: {
      enabled: true,
      syncInterval: 30000,  // 30 seconds
    },
  },
  
  // Security
  security: {
    maxPeers: 50,
    requireAuth: false,
  },
};
`;

    writeFileSync(configPath, config);
    console.log(chalk.green('✓ Created yakmesh.config.js'));

    console.log(chalk.cyan('\n📋 Node Configuration:'));
    console.log(chalk.gray(`   Name:       ${options.name}`));
    console.log(chalk.gray(`   Region:     ${options.region}`));
    console.log(chalk.gray(`   HTTP Port:  ${options.port}`));
    console.log(chalk.gray(`   WS Port:    ${options.wsPort}`));
    console.log(chalk.gray(`   Bootstrap:  ${bootstrapNodes.length} node(s)`));

    console.log(chalk.green('\n✓ Initialization complete!\n'));
    console.log(chalk.white('Next steps:'));
    console.log(chalk.gray('  1. Edit yakmesh.config.js to customize settings'));
    console.log(chalk.gray('  2. Run: npx yakmesh start'));
    console.log('');
  });

// ===== START COMMAND =====
program
  .command('start')
  .description('Start the Yakmesh Node')
  .option('-c, --config <path>', 'Path to config file', './yakmesh.config.js')
  .option('-d, --daemon', 'Run as background daemon')
  .action(async (options) => {
    showBanner();
    
    const configPath = resolve(options.config);
    
    if (!existsSync(configPath)) {
      console.log(chalk.red('✗ Error: yakmesh.config.js not found'));
      console.log(chalk.gray('  Run: npx yakmesh init'));
      process.exit(1);
    }

    console.log(chalk.yellow('Starting Yakmesh Node...\n'));

    // Dynamic import of server - use the package's server module
    const serverPath = join(__dirname, '..', 'server', 'index.js');
    const serverURL = new URL(`file:///${serverPath.replace(/\\/g, '/')}`);
    const { YakmeshNode } = await import(serverURL.href);
    
    // Load config from current working directory
    const configURL = new URL(`file:///${configPath.replace(/\\/g, '/')}`);
    const { default: config } = await import(configURL.href);

    const node = new YakmeshNode(config);

    // Handle shutdown
    process.on('SIGINT', async () => {
      console.log(chalk.yellow('\n\nShutting down...'));
      await node.stop();
      process.exit(0);
    });

    process.on('SIGTERM', async () => {
      await node.stop();
      process.exit(0);
    });

    await node.start();
  });

// ===== STATUS COMMAND =====
program
  .command('status')
  .description('Show node status')
  .option('-p, --port <port>', 'HTTP port of local node', '3000')
  .action(async (options) => {
    try {
      const response = await fetch(`http://localhost:${options.port}/health`);
      const data = await response.json();

      showBanner();
      console.log(chalk.green('✓ Node is running\n'));
      console.log(chalk.cyan('📊 Status:'));
      console.log(chalk.gray(`   Node ID:    ${data.nodeId}`));
      console.log(chalk.gray(`   Peers:      ${data.peers}`));
      console.log(chalk.gray(`   Algorithm:  ${data.algorithm}`));
      console.log('');
    } catch (e) {
      console.log(chalk.red('✗ Node is not running'));
      console.log(chalk.gray(`  Could not connect to http://localhost:${options.port}`));
      process.exit(1);
    }
  });

// ===== PEERS COMMAND =====
program
  .command('peers')
  .description('List connected peers')
  .option('-p, --port <port>', 'HTTP port of local node', '3000')
  .action(async (options) => {
    try {
      const response = await fetch(`http://localhost:${options.port}/peers`);
      const peers = await response.json();

      showBanner();
      
      if (peers.length === 0) {
        console.log(chalk.yellow('No peers connected\n'));
        return;
      }

      console.log(chalk.cyan(`📡 Connected Peers (${peers.length}):\n`));
      
      for (const peer of peers) {
        const ago = Math.floor((Date.now() - peer.lastSeen) / 1000);
        console.log(chalk.white(`  ${peer.name}`));
        console.log(chalk.gray(`    ID:        ${peer.nodeId.slice(0, 24)}...`));
        console.log(chalk.gray(`    Endpoint:  ${peer.endpoint || 'inbound'}`));
        console.log(chalk.gray(`    Last seen: ${ago}s ago`));
        console.log('');
      }
    } catch (e) {
      console.log(chalk.red('✗ Could not fetch peers'));
      console.log(chalk.gray(`  Is the node running on port ${options.port}?`));
      process.exit(1);
    }
  });

// ===== INFO COMMAND =====
program
  .command('info')
  .description('Show detailed node information')
  .option('-p, --port <port>', 'HTTP port of local node', '3000')
  .action(async (options) => {
    try {
      const [nodeRes, replRes] = await Promise.all([
        fetch(`http://localhost:${options.port}/node`),
        fetch(`http://localhost:${options.port}/replication`),
      ]);
      
      const node = await nodeRes.json();
      const repl = await replRes.json();

      showBanner();
      console.log(chalk.cyan('🦬 Node Information:\n'));
      
      console.log(chalk.white('  Identity:'));
      console.log(chalk.gray(`    Node ID:      ${node.nodeId}`));
      console.log(chalk.gray(`    Name:         ${node.name}`));
      console.log(chalk.gray(`    Region:       ${node.region}`));
      console.log(chalk.gray(`    Algorithm:    ${node.algorithm} (NIST Level ${node.nistLevel})`));
      console.log(chalk.gray(`    Created:      ${new Date(node.createdAt).toISOString()}`));
      
      console.log(chalk.white('\n  Capabilities:'));
      for (const cap of node.capabilities) {
        console.log(chalk.gray(`    • ${cap}`));
      }
      
      console.log(chalk.white('\n  Replication:'));
      console.log(chalk.gray(`    Log entries:  ${repl.replicationLogSize}`));
      console.log(chalk.gray(`    Peer states:  ${repl.peerStates.length}`));
      console.log(chalk.gray(`    Tables:       ${repl.replicatedTables.join(', ')}`));
      
      console.log(chalk.white('\n  Public Key (ML-DSA-65):'));
      console.log(chalk.gray(`    ${node.publicKey.slice(0, 64)}...`));
      console.log('');
    } catch (e) {
      console.log(chalk.red('✗ Could not fetch node info'));
      process.exit(1);
    }
  });

// ===== JOIN COMMAND =====
program
  .command('join <endpoint>')
  .description('Connect to a peer node')
  .option('-p, --port <port>', 'HTTP port of local node', '3000')
  .action(async (endpoint, options) => {
    try {
      const response = await fetch(`http://localhost:${options.port}/connect`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ endpoint }),
      });
      
      const result = await response.json();
      
      if (result.success) {
        console.log(chalk.green(`✓ Connected to ${endpoint}`));
      } else {
        console.log(chalk.red(`✗ Failed to connect: ${result.error}`));
      }
    } catch (e) {
      console.log(chalk.red('✗ Could not connect'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

// ===== PROTOCOL COMMAND GROUP =====
const protocolCmd = program
  .command('protocol')
  .description('Manage yak:// protocol registration');

protocolCmd
  .command('register')
  .description('Register yak:// protocol with the operating system')
  .option('-p, --port <port>', 'HTTP port of local node', '3000')
  .action(async (options) => {
    showBanner();
    console.log(chalk.yellow('Registering yak:// protocol...\n'));
    
    try {
      const { YakProtocolHandler } = await import('../protocol/yak-protocol.js');
      const handler = new YakProtocolHandler({ port: parseInt(options.port) });
      
      const success = await handler.register();
      
      if (success) {
        console.log(chalk.green('\n✓ yak:// protocol registered successfully!\n'));
        console.log(chalk.cyan('Try these URLs:'));
        console.log(chalk.gray('  yak://dashboard   - Node dashboard'));
        console.log(chalk.gray('  yak://site        - Hosted website'));
        console.log(chalk.gray('  yak://peers       - Connected peers'));
        console.log(chalk.gray('  yak://content/<hash> - Content by hash'));
        console.log('');
      } else {
        console.log(chalk.red('✗ Failed to register protocol'));
        process.exit(1);
      }
    } catch (e) {
      console.log(chalk.red('✗ Error registering protocol'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

protocolCmd
  .command('unregister')
  .description('Unregister yak:// protocol from the operating system')
  .action(async () => {
    showBanner();
    console.log(chalk.yellow('Unregistering yak:// protocol...\n'));
    
    try {
      const { YakProtocolHandler } = await import('../protocol/yak-protocol.js');
      const handler = new YakProtocolHandler();
      
      await handler.unregister();
      console.log(chalk.green('✓ yak:// protocol unregistered'));
    } catch (e) {
      console.log(chalk.red('✗ Error unregistering protocol'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

protocolCmd
  .command('test <url>')
  .description('Test a yak:// URL without opening browser')
  .option('-p, --port <port>', 'HTTP port of local node', '3000')
  .action(async (url, options) => {
    try {
      const { parseYakUrl, yakToHttp } = await import('../protocol/yak-protocol.js');
      
      const parsed = parseYakUrl(url);
      const httpUrl = yakToHttp(url, parseInt(options.port));
      
      console.log(chalk.cyan('\n🔗 YAK:// Protocol Test\n'));
      console.log(chalk.white('Input:'));
      console.log(chalk.gray(`  ${url}\n`));
      console.log(chalk.white('Parsed:'));
      console.log(chalk.gray(`  Type:   ${parsed.type}`));
      console.log(chalk.gray(`  Route:  ${parsed.route || parsed.hash || parsed.name || '-'}`));
      console.log(chalk.gray(`  Path:   ${parsed.path}\n`));
      console.log(chalk.white('HTTP URL:'));
      console.log(chalk.green(`  ${httpUrl}`));
      console.log('');
    } catch (e) {
      console.log(chalk.red('✗ Error parsing URL'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

protocolCmd
  .command('open <url>')
  .description('Open a yak:// URL in the default browser')
  .option('-p, --port <port>', 'HTTP port of local node', '3000')
  .action(async (url, options) => {
    try {
      const { YakProtocolHandler } = await import('../protocol/yak-protocol.js');
      const handler = new YakProtocolHandler({ port: parseInt(options.port) });
      
      console.log(chalk.cyan(`\n🔗 Opening: ${url}\n`));
      await handler.handle(url);
    } catch (e) {
      console.log(chalk.red('✗ Error opening URL'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

// ===== BOOKMARK SUBCOMMANDS =====
const bookmarkCmd = protocolCmd
  .command('bookmark')
  .alias('bm')
  .description('Manage yak:// URL bookmarks (local pet names)');

bookmarkCmd
  .command('add <name> <target>')
  .description('Add a bookmark (e.g., yakmesh protocol bookmark add alice yak://content/abc123)')
  .action(async (name, target) => {
    try {
      const { getBookmarkManager } = await import('../protocol/yak-protocol.js');
      const bookmarks = getBookmarkManager();
      
      // Handle yak:// prefix in target
      if (target.startsWith('yak://')) {
        target = target.replace(/^yak:\/\//i, '');
      }
      
      const success = bookmarks.add(name, target);
      
      if (success) {
        console.log(chalk.green(`\n✓ Bookmark added: yak://${name.toLowerCase()} → ${bookmarks.get(name.toLowerCase())}\n`));
        console.log(chalk.cyan('Usage:'));
        console.log(chalk.gray(`  yakmesh protocol open yak://${name.toLowerCase()}`));
        console.log(chalk.gray(`  yakmesh protocol test yak://${name.toLowerCase()}`));
      } else {
        console.log(chalk.yellow(`\n⚠ Could not add bookmark '${name}' - it may be a builtin route\n`));
      }
      console.log('');
    } catch (e) {
      console.log(chalk.red('✗ Error adding bookmark'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

bookmarkCmd
  .command('remove <name>')
  .alias('rm')
  .description('Remove a bookmark')
  .action(async (name) => {
    try {
      const { getBookmarkManager } = await import('../protocol/yak-protocol.js');
      const bookmarks = getBookmarkManager();
      
      if (!bookmarks.has(name)) {
        console.log(chalk.yellow(`\n⚠ Bookmark '${name}' not found\n`));
        process.exit(1);
      }
      
      bookmarks.remove(name);
      console.log(chalk.green(`\n✓ Bookmark '${name}' removed\n`));
    } catch (e) {
      console.log(chalk.red('✗ Error removing bookmark'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

bookmarkCmd
  .command('list')
  .alias('ls')
  .description('List all bookmarks')
  .action(async () => {
    try {
      const { getBookmarkManager } = await import('../protocol/yak-protocol.js');
      const bookmarks = getBookmarkManager();
      
      const all = bookmarks.list();
      const names = Object.keys(all);
      
      console.log(chalk.cyan('\n📖 YAK:// Bookmarks\n'));
      
      if (names.length === 0) {
        console.log(chalk.gray('  No bookmarks yet.'));
        console.log(chalk.gray('  Add one with: yakmesh protocol bookmark add <name> <target>'));
      } else {
        for (const name of names.sort()) {
          const bm = all[name];
          console.log(chalk.white(`  yak://${name}`));
          console.log(chalk.gray(`    → ${bm.target}`));
        }
        console.log(chalk.gray(`\n  Total: ${names.length} bookmark(s)`));
      }
      console.log('');
    } catch (e) {
      console.log(chalk.red('✗ Error listing bookmarks'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

bookmarkCmd
  .command('get <name>')
  .description('Get details of a specific bookmark')
  .action(async (name) => {
    try {
      const { getBookmarkManager, yakToHttp } = await import('../protocol/yak-protocol.js');
      const bookmarks = getBookmarkManager();
      
      const target = bookmarks.get(name);
      
      if (!target) {
        console.log(chalk.yellow(`\n⚠ Bookmark '${name}' not found\n`));
        process.exit(1);
      }
      
      const all = bookmarks.list();
      const bm = all[name.toLowerCase()];
      
      console.log(chalk.cyan(`\n📖 Bookmark: ${name}\n`));
      console.log(chalk.white('Details:'));
      console.log(chalk.gray(`  URL:     yak://${name.toLowerCase()}`));
      console.log(chalk.gray(`  Target:  ${target}`));
      console.log(chalk.gray(`  HTTP:    ${yakToHttp('yak:/' + target)}`));
      if (bm?.createdAt) {
        console.log(chalk.gray(`  Created: ${new Date(bm.createdAt).toLocaleString()}`));
      }
      console.log('');
    } catch (e) {
      console.log(chalk.red('✗ Error getting bookmark'));
      console.log(chalk.gray(`  ${e.message}`));
      process.exit(1);
    }
  });

// ===== VERSION =====
program
  .version(VERSION)
  .description('Yakmesh Network - Post-Quantum Decentralized Node');

// Parse arguments
program.parse();

// Show help if no command
if (!process.argv.slice(2).length) {
  showBanner();
  program.outputHelp();
}



